apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - legacy/cnpg-operator.yaml
  - legacy/postgres-shared.yaml
  - infra/infra.yaml
  - infra/observability.yaml
  - apps/adguard.yaml
  - apps/firecrawl.yaml
  - apps/libreplay.yaml
  - apps/litellm.yaml
  - apps/n8n.yaml
  - apps/shopify-bundles.yaml
  - apps/shopify-label.yaml
  - apps/shopify-picker.yaml
  - apps/shopify-sii.yaml
  - apps/socialmedia.yaml
  - apps/teslamate.yaml
  - argocd/ingressroute.yaml
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    patch: |-
      - op: add
        path: /spec/ignoreDifferences
        value:
          - group: external-secrets.io
            kind: ExternalSecret
            jqPathExpressions:
              - .spec.data[]?.remoteRef.conversionStrategy
              - .spec.data[]?.remoteRef.decodingStrategy
              - .spec.data[]?.remoteRef.metadataPolicy
              - .spec.data[]?.remoteRef.nullBytePolicy
              - .spec.dataFrom[]?.extract.conversionStrategy
              - .spec.dataFrom[]?.extract.decodingStrategy
              - .spec.dataFrom[]?.extract.metadataPolicy
              - .spec.dataFrom[]?.extract.nullBytePolicy
          - group: postgresql.cnpg.io
            kind: Cluster
            managedFieldsManagers:
              - manager
