apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-observability
  namespace: argocd
  labels:
    e-dani.com/tier: infra
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/pocharlies/k8s-observability-pocharlies
    targetRevision: deploy/prod
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
