apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/GitHub: https://github.com/emberstack/kubernetes-reflector
  labels:
    e-dani.com/tier: infra
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  sources:
    - repoURL: ghcr.io/emberstack/helm-charts
      chart: reflector
      targetRevision: 10.0.65
      helm:
        releaseName: reflector
        valueFiles:
          - $values/infra/reflector/values.yaml
    - repoURL: https://github.com/pocharlies-org/k8s-gitops-pocharlies
      targetRevision: deploy/prod
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: reflector
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
