#!/usr/bin/env python3
"""Generate ArgoCD repository registration secrets for full Repositories inventory.
Public git repos (URL-only, no creds) + public Helm chart repos. The 3 private
repos (jarvis/brain SSH, auto-reply-worker) are already registered out-of-band
and intentionally NOT redefined here (their creds live outside Git)."""

GIT_PUBLIC = [
    "https://github.com/pocharlies-org/k8s-gitops-pocharlies",
    "https://github.com/pocharlies-org/k8s-shopify-affiliate-pocharlies",
    "https://github.com/pocharlies-org/k8s-shopify-chatbot-pocharlies",
    "https://github.com/pocharlies-org/k8s-shopify-collections-tree-pocharlies",
    "https://github.com/pocharlies-org/k8s-skirmbooks-pocharlies",
    "https://github.com/pocharlies-org/k8s-litellm-pocharlies",
    "https://github.com/pocharlies/k8s-adguard-pocharlies",
    "https://github.com/pocharlies/k8s-ai-pocharlies",
    "https://github.com/pocharlies/k8s-firecrawl-pocharlies",
    "https://github.com/pocharlies/k8s-infra-pocharlies",
    "https://github.com/pocharlies/k8s-libreplay-pocharlies",
    "https://github.com/pocharlies/k8s-n8n-pocharlies",
    "https://github.com/pocharlies/k8s-observability-pocharlies",
    "https://github.com/pocharlies/k8s-shopify-bundles-pocharlies",
    "https://github.com/pocharlies/k8s-shopify-label-pocharlies",
    "https://github.com/pocharlies/k8s-shopify-picker-pocharlies",
    "https://github.com/pocharlies/k8s-shopify-sii-pocharlies",
    "https://github.com/pocharlies/k8s-shopify-translations-pocharlies",
    "https://github.com/pocharlies/k8s-socialmedia-pocharlies",
    "https://github.com/pocharlies/k8s-teslamate-pocharlies",
]

HELM_PUBLIC = {
    "cloudnative-pg": "https://cloudnative-pg.github.io/charts",
    "grafana": "https://grafana.github.io/helm-charts",
    "prometheus-community": "https://prometheus-community.github.io/helm-charts",
    "victoria-metrics": "https://victoriametrics.github.io/helm-charts",
}


def git_secret(url):
    short = url.rsplit("/", 1)[-1]
    return f"""apiVersion: v1
kind: Secret
metadata:
  name: repo-{short}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  name: {short}
  url: {url}
"""


def helm_secret(name, url):
    return f"""apiVersion: v1
kind: Secret
metadata:
  name: repo-helm-{name}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: {name}
  url: {url}
  enableOCI: "false"
"""


docs = []
docs.append("# Declarative ArgoCD repository inventory (managed by the 'root' app-of-apps).")
docs.append("# Public repos: URL-only, no credentials. Private repos (jarvis/brain/auto-reply)")
docs.append("# are registered out-of-band with their secrets and are NOT redefined here.")
docs.append("# Generated by gen_repositories.py — edit the generator, not this file by hand.")
parts = ["\n".join(docs)]
parts += [git_secret(u) for u in GIT_PUBLIC]
parts += [helm_secret(n, u) for n, u in HELM_PUBLIC.items()]

with open("/home/dibanez/k8s/k8s-gitops-pocharlies/argocd/repositories.yaml", "w") as fh:
    fh.write("---\n".join(p.rstrip() + "\n" for p in parts))

print(f"wrote {len(GIT_PUBLIC)} git + {len(HELM_PUBLIC)} helm repository secrets")
