apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocharlies-webgui
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/GitHub: https://github.com/pocharlies-org/k8s-pocharlies-webgui-pocharlies
  labels:
    e-dani.com/portfolio: skirmshop
    e-dani.com/tier: app
    e-dani.com/activation: disabled
spec:
  project: default
  source:
    repoURL: https://github.com/pocharlies-org/k8s-pocharlies-webgui-pocharlies
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: skirmshop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
