apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zombie-data
  namespace: longhorn-zombie-test
  labels:
    app: longhorn-zombie-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
