apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dgx-synapse-mcp
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/GitHub: https://github.com/pocharlies-org/k8s-dgx-synapse-mcp-pocharlies
  labels:
    e-dani.com/tier: app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pocharlies-org/k8s-dgx-synapse-mcp-pocharlies
    targetRevision: deploy/prod
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: dgx-synapse-mcp
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
