apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jarvis
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/GitHub: https://github.com/pocharlies/k8s-jarvis-pocharlies
  labels:
    e-dani.com/tier: app
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: git@github.com:pocharlies/k8s-jarvis-pocharlies.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
