apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-stg
  namespace: argocd
  labels:
    e-dani.com/tier: app
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    link.argocd.argoproj.io/GitHub: https://github.com/pocharlies/k8s-n8n-pocharlies
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/pocharlies/k8s-n8n-pocharlies
    targetRevision: stg
    path: k8s/overlays/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-stg
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
