apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopify-collections-tree
  namespace: argocd
  labels:
    e-dani.com/portfolio: skirmshop
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/pocharlies/k8s-shopify-collections-tree-pocharlies
    targetRevision: deploy/prod
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: skirmshop
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
