apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skirmshop-drive-mirror
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/GitHub: https://github.com/pocharlies-org/k8s-skirmshop-drive-mirror-pocharlies
  labels:
    e-dani.com/tier: infra
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/pocharlies-org/k8s-skirmshop-drive-mirror-pocharlies
    targetRevision: deploy/prod
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: backup-hub
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
